### ISSUE TITLE
"Can be killed" field resets after reload

### ISSUE THREAD

**Issue by NlL5** [mchorse/blockbuster#10]
The 'Can be killed' fiels resets after unloading and loading the game again. Steps to reproduce:

1. Change _Can be killed_ to _No_ with the Actor configuration device. (The Invulnerable tag of the Actor will change to 1.)
2. Save and exit the world.
3. Load the world again. (The Invulnerable tag is still 1!)
4. Rightclick the Actor with the Actor configuration device. The GUI will display _Yes_.

**Comment by mchorse** [comment]
Indeed... I think it's just how minecraft works, for some reason, `Invulnerability` tag doesn't synchronize with client, what a shame :pensive:

Fixed in bbfb9cf6aa7bb48da71fe96b990c9f9b8514c8e5.
