### ISSUE TITLE
Name Tag's are broken? 

### ISSUE THREAD

**Issue by DinTurbo** [mchorse/blockbuster#106]
Hello! I'm not sure if it is a bug or not. Most likely not but I see no way around it. It has to do with the "Name Tag" and how it works.

Edit: 
The Name Tag's are broken. The "over head" names are just random. Restarting minecraft gives different results. Or more like if you do it one way gives one result until restart. 

It randomly likes to work close up or at distance, or strait out just not even display anything. But restarting and just giving it a descent shake will give you the desired look. Just random and buggy :c I have no ide how it works but just restarting and playing around with it before recording and you might just get what you want.

**Comment by mchorse** [comment]
Name tags aren't broken. Maybe a shader pack you're using causing those issues? The way name tag works, it gives a name tag to the actor in same way as a vanilla name tag item forged with an anvil would.

**Comment by DinTurbo** [comment]
Strange. 

Recording a chicken right now using the "Animal morph" with "Name Tag" TEss. In playback the name tag is displaying like a player name. That is how I expected it to work from older versions of blockbuster and what I made with it.  But with "Blockbuster Alex" with "Name Tag" ASsssss I have to walk up close to see the name. (and it is allot darker like a minecraft mob name tag is)

I have removed my shades before I reported it. Optifine is to good to remove. :)
Not sure what or how this should work. But I know before I had reocred some stuff with "Name Tag" to give my actor real usersnames.

**Comment by mchorse** [comment]
If you want for actors to always display a name, you must enable Blockbuster > Actor > "Always render actor name tags" in mod options. Name tags showing up only when you look at the actor is default behavior, and it's intended.

**Comment by DinTurbo** [comment]
Well ok!  But still odd how some morphs act like the name tag box is a username floating thing. :)

Now all Blockbuster morphs you have to download and extract act the same way. But the morphs you get just installing the mod and not this new "Blockbuster morphs" do not behave the same way.  Meh... All good then! Had no ide about that enable thing. 

Just found it very odd how different and odd everything was working trying to figure out how to give my actors usernames. It just was as if something was wrong with the blockbuster morphs.

**Comment by mchorse** [comment]
Yeah, indeed, the problem there is different rendering methods which are used by entity morphs, custom model morphs, actor entities or fake player entities.

You can also take a look at the vanilla [mob model pack](https://drive.google.com/open?id=1gM0Timn6aKwx_H4sTbo1mXhrG-APUsYM). It has most of vanilla mobs.
