### ISSUE TITLE
Screen bugging out everytime I get on a world and look around

### ISSUE THREAD

**Issue by KattinKattYouTube** [mchorse/blockbuster#134]
![ezgif-1-b4335d0d7c88](https://user-images.githubusercontent.com/33800796/84554763-03d1ff80-acdf-11ea-8d44-a16e5c70b76f.gif)

It looks like I'm crouching but I'm not...How can I fix this? It goes faster than this, but when I'm recording it slows down.

**Comment by mchorse** [comment]
From Metamorph's FAQ:
> **Q: My screen goes up and down. How to fix?**
> A: Most likely you installed MorePlayerModels mod alongside Metamorph. To fix that, either go to Mod Options > Metamorph > General and enable Disable POV option, or disable POV option in MPM's config and restart the game.
