### ISSUE TITLE
Bug report: [Internal server crash/shudown/kick : Payload may not be larger than 32767 bytes] when making multiple complex Emoticons model action in sequencer

### ISSUE THREAD

**Issue by LIII-Works** [mchorse/blockbuster#144]
Bug report: [Internal server crash/shutdown/kick: Payload may not be larger than 32767 bytes] when making complex Emoticons model action
-----------------------------------------
Mod Version:
   Blockbuster : blockbuster-2.0.2-1.12.2
   Emoticons: emoticons-0.5-1.12.2-dist

  When a complex action was made with blockbuster creating multiple emoticon model (complex) in a sequencer will cause a server shutdown/kick. The game did not crash, just being kicked out from the singleplayer world. Multiplayer not tested.

  The world and modpack has been attached. You can try to duplicate a Morph in Scene S6-Mem Cast_1 sequencer.
[World.zip](https://github.com/mchorse/blockbuster/files/5113951/World.zip)
[modpack.zip](https://github.com/mchorse/blockbuster/files/5113954/modpack.zip)

[Video Showcase](https://streamable.com/7ty39u)

**Comment by mchorse** [comment]
There is no fix, but there is a workaround. You can increase the max packet size in McLib’s vanilla tweaks options, as shown here: https://youtu.be/96_VnqywyRY?t=239
