### ISSUE TITLE
Wolf ears model shows folder name as nametag

### ISSUE THREAD

**Issue by KattinKattYouTube** [mchorse/blockbuster#157]
![Minecraft 1 12 2 11_3_2020 7_51_29 PM](https://user-images.githubusercontent.com/33800796/98059973-1c69c000-1e0e-11eb-88f2-0cce2371365c.png)

I can't figure out how to get it to stop, there is no name for it in edit mode, so I don't know why it is showing the folder name ("Black_Wolf_Ears"). Any help would be great!

**Comment by mchorse** [comment]
That's not Metamorph's issue. 😑

The issue here is that you installed the model, and then renamed the folder. Watch this [excerpt](https://youtu.be/33S4PFVuygc?t=465).
