### ISSUE TITLE
Every time I enter camera edit mode, it undoes things I've created in my world

### ISSUE THREAD

**Issue by KattinKattYouTube** [mchorse/blockbuster#158]
I recorded a scene with an actor after creating a room for the scene. When I pressed "C", it removed everything in that room and placed some weird Decocraft item around the school. I tried to replay the scene by pressing right Ctrl, but it only showed my actor and didn't put anything back. Sorry to bother you again, McHorse. Hopefully, this will be the last time.
![Minecraft 1 12 2 11_5_2020 8_40_59 AM](https://user-images.githubusercontent.com/33800796/98257073-de22ec80-1f44-11eb-9802-0856032750ab.png)

**Comment by mchorse** [comment]
That happens when damage control feature enabled and Decocraft items get affected in any way. [Watch this video](https://www.youtube.com/watch?v=hpmDiuODqnc).

> McHorse. Hopefully, this will be the last time.

For future issues or questions I would suggest joining [my Discord server](https://discord.gg/qfxrqUF) where I'll be glad to help.
