### ISSUE TITLE
Rendering and actor issues (1.3.1 dev)

### ISSUE THREAD

**Issue by NlL5** [mchorse/blockbuster#16]
Following issues are found in commit 535df63.

- [x] Newly difference in model rendering with McME and blockbuster. I'll send you model and skin via mail.
- [x] When stopping a playback while an Actor is riding a horse/pig, the Actor won't be reset to it's start position. Thus, on the next playback the Actor will stay sitting on the horse/pig the whole playback [until he gets off]. But I guess this issue will be fixed with blockbuster 1.4.
(And the sitting animation isn't completely right, but this should be fixed with 1.4 as well, I think.)
- [x] Track mount's position and rotation (added by @mchorse)
- [x] Sometimes Actors disappear, even if they're not leaving the screen: https://youtu.be/CAWDLUZu1Io
- [x] In Minecraft controls: What do you think about "Increase duration" as counterpart to "Reduce"? :wink: 
- [x] If an Actor (that's attached to a director block) gets killed, he doesn't get detached automatically. So when starting the playback of the director block, the playback won't stop until you stop it manually.

### Things I'm not sure about

- [x] Undocumented feature: `Record [...] (difference in 25t)`. Should it be "difference is"?
And every mark has "(x1)," in it, even for different Actors. (Well, the feature is undocumented, so I think I just don't know what this means :D)

### High-level beauty stuff

- [x] `/director play|stop` will always say that the playback has started / stopped, even if it's already started / stopped. (Instead of something like "Director block at ( , , ) is currently running" or so.)

**Comment by mchorse** [comment]
> Newly difference in model rendering with McME and blockbuster. I'll send you model and skin via mail.

Yeah, I noticed it too, my sheeps are ruined 😭 

> Sometimes Actors disappear, even if they're not leaving the screen:

Yeah, I noticed it too, but not really sure why it happens. I tried only one thing, right now, is looking at the AABB (maybe it just some rendering bug) but no. I'm really curious why it happens, but I'll start investigation after I'll finish with [one project](https://twitter.com/McHorsy/status/793785050298998785), first :smirk:

> In Minecraft controls: What do you think about "Increase duration" as counterpart to "Reduce"?

That should be moved to `High-level beauty stuff` :D

I agree on this, though!

> If an Actor (that's attached to a director block) gets killed, he doesn't get detached automatically. So when starting the playback of the director block, the playback won't stop until you stop it manually.

Now that I'm acknowledged, I'll fix that. Thanks :)

> Should it be "difference is"?

Probably, yes. Doh, those language semantics :D

> And every mark has "(x1)," in it, even for different Actors.

`(x1)` means the delay between frames. If set delay between frames, for example, `3` you'll get `(x3)` and the current ticks will be multiplied by `3` (so you didn't had to multiply it yourself). `x1` is the most smoothest recording, however `x2` is sufficient enough to use too.

> `/director play|stop` will always say that the playback has started / stopped, even if it's already started / stopped. (Instead of something like "Director block at ( , , ) is currently running" or so.)

Good idea! Accepted.

Thank you so much for testing and reporting all of that stuff! I probably missed most of these stuff if you didn't noticed :smile:

I should probably do more testing lol :D

**Comment by NlL5** [comment]
> Yeah, I noticed it too, my sheeps are ruined :sob: 

Oh no :frowning_face: 

> I'm really curious why it happens, but I'll start investigation after I'll finish with one project, first :smirk:

Haha :D This guy..

> (x1) means the delay between frames. If set delay between frames, for example, 3 you'll get (x3) and the current ticks will be multiplied by 3 (so you didn't had to multiply it yourself). x1 is the most smoothest recording, however x2 is sufficient enough to use too.

Ah I see :thinking: Oh wow, this is the first time that I looked at the blockbuster settings :O

> Thank you so much for testing and reporting all of that stuff! I probably missed most of these stuff if you didn't noticed :smile:
I should probably do more testing lol :D

You're welcome! It's always harder to find problems if you're the developer ;-)

**Comment by mchorse** [comment]
> When stopping a playback while an Actor is riding a horse/pig, the Actor won't be reset to it's start position. Thus, on the next playback the Actor will stay sitting on the horse/pig the whole playback [until he gets off]. But I guess this issue will be fixed with blockbuster 1.4.
(And the sitting animation isn't completely right, but this should be fixed with 1.4 as well, I think.)

I don't think it will be fixed in 1.4, since it's not the custom behavior. Not really sure how to put this in words, but I'll have to reset (unmount and reset actor and the pig) manually. About animations, I think I totally forgot to add a riding pose for custom models, so that's going to be a new thing also :D

**Comment by mchorse** [comment]
> Sometimes Actors disappear, even if they're not leaving the screen

I fixed it (I think, because recording that had this bug now worked perfectly)! 😆 

That was a really severe bug in the playback code. Basically the AABB's of the actors weren't updated during the playback.

The pig/horse issue was fixed also, but now I need to restore the mount's position and rotation recording and playback (I added additional point). Thanks so much for testing stuff out!!! 👍

**Comment by mchorse** [comment]
All issues are fixed, as far as I can tell. Let me know if I missed something 😄

**Comment by NlL5** [comment]
Cool, I'll check it out! :)

**Comment by mchorse** [comment]
I'll close this issue (so exciting ☺️). If you'll find any issues, I'll reopen this issue and fix it.
