### ISSUE TITLE
Blockbuster position issues with Mr. Crayfish's Furniture Mod and UltimateCar Mod

### ISSUE THREAD

**Issue by chrishdx** [mchorse/blockbuster#160]
Hi there,

if I record a scene and use blocks from Crayfish's Furniture Mod or UltimateCar Mod, the replay does not display it correctly. What could be the reason?

![2021-01-23_12 42 56](https://user-images.githubusercontent.com/50511550/105577287-d8d18300-5d78-11eb-929f-27465fc7fa6a.png)

![2021-01-23_12 43 33](https://user-images.githubusercontent.com/50511550/105577291-dff89100-5d78-11eb-8540-0ebc9ba747f4.png)

Crayfish's Furniture Mod Version 6.3.1
UltimateCar Mod 2.0.1
Gameversion 1.12.2
Forge 14.23.5.2854

**Comment by mchorse** [comment]
Blockbuster can’t properly record mounted actors. I don’t think you can do anything about the car. But with chairs you can try removing mounted action like shown [here](https://youtu.be/VQZe44ergjU?t=255).
