### ISSUE TITLE
Blockbuster mods crashes

### ISSUE THREAD

**Issue by LevMine** [mchorse/blockbuster#163]
[debug.log](https://github.com/mchorse/blockbuster/files/5936795/debug.log)

See the log we tried different types of forge and updated java

**Comment by mchorse** [comment]
You haven’t installed correct versions of my mods. [Check compatibility table](https://github.com/mchorse/mclib/wiki/Compatibility-table-of-McHorse's-mods), but from brief look, you have old Blockbuster 1.6 instead of Blockbuster 2.2.
