### ISSUE TITLE
Attaching an audio to a scene does only work for one player at a time on a server

### ISSUE THREAD

**Issue by gewenzsko** [mchorse/blockbuster#175]
Whenever a person attaches an audio (audio sync feature) to a scene on a server, the person who attached a song before will not hear anything anymore.

Example
Person A: Attachs sound to scene X
Person A plays scene X and hears the audio
Person B: Attachs soudn to scene X
Person A: plays scene X and **cannot hear the audio anymore**
------------
Same goes for the other way around:
If person A now attaches the sound back to scene X
Person B will not hear anything while its played.

(This was only tested with 2-3 scenes, I am not sure if this is a possible missing feature or a bug)

_Mods used:
blockbuster 2.2.2
mclib 2.2.2
metamorph 1.2.6
chameleon 1.0.2_

**Comment by mchorse** [comment]
Both of you have same exact audio files in the `config/blockbuster/audio/`? Because Blockbuster doesn’t sync the audio files.

**Comment by gewenzsko** [comment]
Yes indeed. Same audio file / same name / same size and same scene

(If I create a modpack with all the scenes attached and send it to other people it works, but as soon as they try to attach it to a specific scene themselves it won't work for me in that scene anymore)

**Comment by mchorse** [comment]
I'll have to look into that. Thanks for reporting!

**Comment by mchorse** [comment]
I couldn't reproduce it with given steps... 👊😔 

With the agreement of OP we decided to not investigate this bug further. If that ever happens to anyone, try quitting the server before your friend adds a new audio track.
