### ISSUE TITLE
Why no onion skin?

### ISSUE THREAD

**Issue by StayStrange** [mchorse/blockbuster#198]
Not an issue. Just wondering why you never thought of adding an onion skin mode for doing traditional animating. You know like using the pose editor and saving poses frame by frame like key frames. And using an onion skin of the actor your animating to help guide your poses to get a smooth animations.

**Comment by Chryfi** [comment]
Onion skinning is not a usual thing in 3d animation. I don't even know if Blender has it...it is a 2d animation thing.
Also, the next update by NyanLi will have onion skins ;)

**Comment by StayStrange** [comment]
SWEET!!!
