### ISSUE TITLE
2.3.3 incompatible mclib 2.3.6?

### ISSUE THREAD

**Issue by AntiThesis1250** [mchorse/blockbuster#204]
![image](https://user-images.githubusercontent.com/31405319/151329996-86a9346b-10b3-454c-9fb1-6e47ec029954.png)
![image](https://user-images.githubusercontent.com/31405319/151330043-d0dd85e5-2f99-4764-80a7-e7489d7c38d2.png)
![image](https://user-images.githubusercontent.com/31405319/151330072-d7319637-85cc-4671-b293-55ecd7025880.png)

**Comment by AntiThesis1250** [comment]
why not used default

**Comment by mchorse** [comment]
I don’t know

**Comment by AntiThesis1250** [comment]
I can't run this project using idea
I have completed all classes that lack abstract methods
![image](https://user-images.githubusercontent.com/31405319/151333928-2e9302c8-81eb-4236-97bd-8799e271b4ec.png)
but log4j  maybe has a bug

**Comment by AntiThesis1250** [comment]
![image](https://user-images.githubusercontent.com/31405319/151336776-de143ecb-dfe2-44ea-a5c5-345e95b56fff.png)
![image](https://user-images.githubusercontent.com/31405319/151336860-6ed5a79d-12dc-40f2-a9db-12e161198cb0.png)

**Comment by AntiThesis1250** [comment]
i download in this https://github.com/mchorse/blockbuster/releases/tag/2.3.3
but i don't build,source has problem? Could you check it?

**Comment by AntiThesis1250** [comment]
i only want to use particles method, i need spawn snowstorm particle in my mod

**Comment by AntiThesis1250** [comment]
i know 
![image](https://user-images.githubusercontent.com/31405319/151367568-0df99871-b042-49df-9ab6-b71039df589d.png)
2799 can't donwload

**Comment by AntiThesis1250** [comment]
![image](https://user-images.githubusercontent.com/31405319/151516600-53c23f08-50e1-435c-a598-e9e8d2e05fd6.png)
![image](https://user-images.githubusercontent.com/31405319/151516637-2ced69f3-7d01-4b80-9e8c-f822d8fddf0a.png)
Did you do any special processing during compilation?

**Comment by AntiThesis1250** [comment]
@mchorse

**Comment by mchorse** [comment]
In order to build Blockbuster, you need `dev` builds (with MCP), and not the mods you can downloads from CurseForge. Download [these dev builds](https://drive.google.com/file/d/1RYoWTQYpamqluAYWGOwfkKYlMO6mUP9-/view?usp=sharing), place jar files in `run/libs/`, and change back build.gradle the way it was, and after that it should compile.

**Comment by AntiThesis1250** [comment]
ok,There are no problems . thank you

**Comment by mchorse** [comment]
Awesome 👏
