### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by CMSMortal-chen** [mchorse/blockbuster#225]
[spoiler]游戏核心：1.12.2-Forge_14.23.5.2860
启动内存：4096 MB
操作系统：Microsoft Windows 10 专业版 x64
————————————————————
CPU：#0Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz 
内存：8139
显卡：#0NVIDIA GeForce GT 1030 
————————————————————
核心路径：F:\NewCMS1.12\.minecraft\versions\1.12.2-Forge_14.23.5.2860
Java信息：C:\Program Files\Java\jdk1.8.0_291\bin\javaw.exe (Java8.0.2910.10 64 Bit)
BakaXL路径：F:\NewCMS1.12\BakaXL_Public_Ver_3.1.1.1.exe
————————————————————
错误日志：
---- Minecraft 崩溃报告 ----

WARNING: coremods are present:
  ItemPatchingLoader (ItemPhysic_Full_1.4.32_mc1.12.2.jar)
  McLib core mod (mclib-2.4-1.12.2.jar)
  ShaderHookLoader (Minema-3.6.2-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  TickrateChanger (TickrateChanger-1.0.14.jar)
  BlockbusterCore (blockbuster-2.5-1.12.2.jar)
  weaponlib (mw_2.0-0.4.6.2_mc1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  APCoreMod (aperture-1.8-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  CreativePatchingLoader (CreativeCore_v1.10.9_mc1.12.2.jar)
  CoreModLoader (Sound-Physics-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 7/2/22 7:37 PM
崩溃类型： Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1474)
	at mchorse.blockbuster.recording.scene.Scene.worldTick(Scene.java:292)
	at mchorse.blockbuster.recording.scene.SceneManager.worldTick(SceneManager.java:71)
	at mchorse.blockbuster.recording.capturing.ActionHandler.onWorldServerTick(ActionHandler.java:487)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_374_ActionHandler_onWorldServerTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1098625184 bytes (1047 MB) / 4260102144 bytes (4062 MB) up to 4260102144 bytes (4062 MB)
	JVM Flags: 2 total; -Xincgc -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G6_pre1 44 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version         | Source                                            | Signature                                |
	|:------ |:----------------- |:--------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2          | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp               | 9.42            | minecraft.jar                                     | None                                     |
	| LCHIJA | FML               | 8.0.99.99       | forge-1.12.2-14.23.5.2860.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2860    | forge-1.12.2-14.23.5.2860.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0           | minecraft.jar                                     | None                                     |
	| LCHIJA | itemphysic        | 1.4.0           | minecraft.jar                                     | None                                     |
	| LCHIJA | openmodscore      | 0.12.1          | minecraft.jar                                     | None                                     |
	| LCHIJA | dsurroundcore     | 3.5.4.3         | minecraft.jar                                     | None                                     |
	| LCHIJA | mclib             | 2.4             | mclib-2.4-1.12.2.jar                              | None                                     |
	| LCHIJA | metamorph         | 1.3             | metamorph-1.3-1.12.2.jar                          | None                                     |
	| LCHIJA | minema            | 3.6.2           | Minema-3.6.2-1.12.2.jar                           | None                                     |
	| LCHIJA | blockbuster       | 2.5             | blockbuster-2.5-1.12.2.jar                        | None                                     |
	| LCHIJA | aperture          | 1.8             | aperture-1.8-1.12.2.jar                           | None                                     |
	| LCHIJA | forgelin          | 1.8.2           | Forgelin-1.8.2.jar                                | None                                     |
	| LCHIJA | betterfoliage     | 2.2.0           | BetterFoliage-MC1.12-2.2.0.jar                    | None                                     |
	| LCHIJA | chiselsandbits    | 14.33           | chiselsandbits-14.33.jar                          | None                                     |
	| LCHIJA | cmsitem           | 0.0.4           | cmsitem-0.4.jar                                   | None                                     |
	| LCHIJA | commander         | 1.1             | commander-1.1-1.12.2.jar                          | None                                     |
	| LCHIJA | creativecore      | 1.10.0          | CreativeCore_v1.10.9_mc1.12.2.jar                 | None                                     |
	| LCHIJA | damagemark        | 1.4             | DamageMarkMod-1.12.2-1.4.jar                      | None                                     |
	| LCHIJA | ptrmodellib       | 1.0.2           | PTRLib-1.0.2.jar                                  | None                                     |
	| LCHIJA | props             | 2.6.0           | Decocraft-2.6.0_1.12.2.jar                        | None                                     |
	| LCHIJA | mts               | 14.3.1          | Immersive+Vehicles-1.12.2-14.3.1.jar              | None                                     |
	| LCHIJA | dwtmtspack        | 1.0.0           | DWTPack_V1.0.2.jar                                | None                                     |
	| LCHIJA | emoticons         | 1.1             | emoticons-1.1-1.12.2.jar                          | None                                     |
	| LCHIJA | cfm               | 6.2.0           | furniture-6.2.0-1.12.2.jar                        | None                                     |
	| LCHIJA | journeymap        | 1.12.2-5.5.6    | journeymap-1.12.2-5.5.6.jar                       | None                                     |
	| LCHIJA | macrokey          | 1.12-2.0.3.202  | MacroKey+Keybinding-1.12-2.0.3.202.jar            | 70f66ec745a90c2c65d71135b8929bcb4bb87e3c |
	| LCHIJA | mtsofficialpack   | 11.0.0          | MTS_Official_Pack_V11.jar                         | None                                     |
	| LCHIJA | mw                | 0.4.6.2         | mw_2.0-0.4.6.2_mc1.12.2.jar                       | None                                     |
	| LCHIJA | nbtedit           | 1.11.2-2.0.2    | NBTEdit-1.12-2.0.2.jar                            | None                                     |
	| LCHIJA | openmods          | 0.12.1          | OpenModsLib-1.12.2-0.12.1.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks        | 1.8             | OPEN.jar                                          | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | placeableitems    | 3.3             | placeableitems-3.3.jar                            | None                                     |
	| LCHIJA | soundphysics      | 1.0.4           | Sound-Physics-1.12.2.jar                          | None                                     |
	| LCHIJA | tickratechanger   | 1.0.14          | TickrateChanger-1.0.14.jar                        | None                                     |
	| LCHIJA | twilightforest    | 3.11.1021       | twilightforest-1.12.2-3.11.1021-universal.jar     | None                                     |
	| LCHIJA | variedcommodities | 1.12.2          | VariedCommodities_1.12.2-(13Jan22).jar            | None                                     |
	| LCHIJA | worldedit         | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LCHIJA | orelib            | 3.5.2.2         | OreLib-1.12.2-3.5.2.2.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround         | 3.5.4.3         | DynamicSurroundings-1.12.2-3.5.4.3.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UD     | aperture_core     | 1.8             | minecraft.jar                                     | None                                     |
	| UD     | blockbuster_core  | 2.5             | minecraft.jar                                     | None                                     |
	| UD     | mclib_core        | 2.4             | minecraft.jar                                     | None                                     |

	Loaded coremods (and transformers): 
ItemPatchingLoader (ItemPhysic_Full_1.4.32_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
McLib core mod (mclib-2.4-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
ShaderHookLoader (Minema-3.6.2-1.12.2.jar)
  info.ata4.minecraft.minema.shaderHook_coremod.ShaderHookInjector
ForgelinPlugin (Forgelin-1.8.2.jar)
  
TickrateChanger (TickrateChanger-1.0.14.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
BlockbusterCore (blockbuster-2.5-1.12.2.jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
weaponlib (mw_2.0-0.4.6.2_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
APCoreMod (aperture-1.8-1.12.2.jar)
  mchorse.aperture.core.APCoreClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
CreativePatchingLoader (CreativeCore_v1.10.9_mc1.12.2.jar)
  
CoreModLoader (Sound-Physics-1.12.2.jar)
  com.sonicether.soundphysics.CoreModInjector
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Mortal_chen'/107, l='world', x=4137.78, y=66.00, z=6656.94]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G6_pre1
	OptiFine Build: 20210323-161358
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 497.29
	OpenGlRenderer: NVIDIA GeForce GT 1030/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

[/spoiler]

**Comment by Chryfi** [comment]
Thank you for the report, I will look into it
