### ISSUE TITLE
Editing not showing?

### ISSUE THREAD

**Issue by MeepDaSheep** [mchorse/blockbuster#227]
I can open the editor, edit things, but i cant play the scene while in the editor for some reason.

**Comment by mchorse** [comment]
This isn't an appropriate place to ask for help, but rather to submit bug/crash reports. If you need help with the mod, join this [Discord server](https://discord.gg/qfxrqUF). As for the question, it sounds like you didn't pressed Edit camera button. Check this [video tutorial](https://www.youtube.com/watch?v=VfSZs4f7Dx0).
