### ISSUE TITLE
VanillaFix gives Error when Placing/Modifying Actors

### ISSUE THREAD

**Issue by PilotgamerGuy** [mchorse/blockbuster#229]
MultiMC Log:
https://paste.ee/p/dEJ0C

VanillaFix Log:
[crash-2022-09-12_17.25.58-server.txt](https://github.com/mchorse/blockbuster/files/9552582/crash-2022-09-12_17.25.58-server.txt)

Note: The game didn't crash, just VanillaFix stored the log as a crash report.

**Comment by Chryfi** [comment]
Fixed in BB 2.6 update. You can download it on the mchorse discord in the dev-builds by getting dev-build-tester role.
