### ISSUE TITLE
Bug with the gamertags

### ISSUE THREAD

**Issue by ShadesRaith** [mchorse/blockbuster#23]
I've tried 3 different gamertag removal commands/Mods which all work when in non morph state but i cant hide the tags at when in any morph. If it would not be to hard can you fix/implement a way to hide the name in mob state for sort of mob camouflage hiding purpose.
![capture](https://cloud.githubusercontent.com/assets/27860302/25498093/f840e5d4-2b43-11e7-9465-985f67eed911.PNG)
![capture2](https://cloud.githubusercontent.com/assets/27860302/25498180/4983eb08-2b44-11e7-851e-099beb171564.PNG)

**Comment by ShadesRaith** [comment]
Oh and the rain is just something another mod did i tested morph by itself and rain did hurt enderman so don't worry about that bit in the first picture

**Comment by mchorse** [comment]
@ShadesRaith this is repository for Blockbuster bugs, next time, please post to [Metamorph issues](https://github.com/mchorse/metamorph).
