### ISSUE TITLE
Game crashes after stopping recording

### ISSUE THREAD

**Issue by BOTFerris** [mchorse/blockbuster#237]
The title says it all. Not sure if it's blockbuster or my other mods so I thought I'd post the crash report here.
[crash-2023-02-13_18.24.16-server.txt](https://github.com/mchorse/blockbuster/files/10723732/crash-2023-02-13_18.24.16-server.txt)

**Comment by Chryfi** [comment]
It's a journeyMap issue. The incompatibility will is fixed in the upcoming update, until then remove that mod.

**Comment by BOTFerris** [comment]
> It's a journeyMap issue. The incompatibility will is fixed in the upcoming update, until then remove that mod.

Ah thanks. Is there a set date on when the said update is released or does it come out when it's fully polished?

**Comment by Chryfi** [comment]
There is no set date atm, as I have no time currently.
