### ISSUE TITLE
Game crashes when trying to record a Actor Movement that is longer than ~470 ticks

### ISSUE THREAD

**Issue by Brxnni** [mchorse/blockbuster#239]
The game crashes with the following error: Payload may not be lager than 32767 bytes. (I have tried to increase the max. packet size from client to server, but this didn't make a difference)

latest.log:
[latest.log](https://github.com/mchorse/blockbuster/files/11362288/latest.log)

**Comment by Chryfi** [comment]
You have to increase the Maximim packet size in the mclib settings.
