### ISSUE TITLE
Try to support for new versions of MC every 3 years

### ISSUE THREAD

**Issue by DannyDevPro** [mchorse/blockbuster#242]
Backward will eventually be eliminated

**Comment by Chryfi** [comment]
Thanks for the genius idea. If it just would be so easy, wow why didn't McHorse or I come up with this ourselves? Oh, if we just had this idea we would have ported the whole time. Porting is so easy, and rewriting everything from scratch is even easier.

**Comment by mchorse** [comment]
How about you just enjoy the current version of the mod? What's the problem with it being on 1.12.2? And what Blockbuster would benefit from updating to a newer version?
