### ISSUE TITLE
Performance Issues 

### ISSUE THREAD

**Issue by InfinitePlayz23** [mchorse/blockbuster#247]
I'm having issues with the blockbuster mod, when I start a scene with the playback button major lag begins and my fps drops down to 4 or 15. I've tried everything down to changing my ram to downloading better performance mods and nothing seems to work, I want to mention i'm also using optifine shaders. If anyone has or is experiencing the same issue and found a way to reduce or fix the issue let me know, I would like for my scenes to be much smoother. I allocate 8GB of ram into the launcher just for anyone wondering.

![2023-07-10_10 07 54](https://github.com/mchorse/blockbuster/assets/61270680/c391d6e9-b68a-4cf9-a43e-08a4fd414985)

PC SPECS: 

AMD Ryzen 3700X 8-Core Processor
Radeon RX 580 Series 
CPU - 16 RAM
AMD Radeon Graphics Processor (0x67DF)
CYBERPOWER PC TOWER
64-bit operating system, x64-based processor

**Comment by mchorse** [comment]
This issue isn't because of Blockbuster mod, it's because of Emoticons mod. Either stop using Emoticons morphs or change to `_simple` variants.
