### ISSUE TITLE
used camera editor and game crashed

### ISSUE THREAD

**Issue by hazmatguy88778** [mchorse/blockbuster#253]
i used the camera editor and was working on a manual camera fixture, and all the sudden the game crashed after the time limit ended, tried to rejoin and play the scene multiple times but it keeps crashing

**Comment by mchorse** [comment]
Go to another world, and do like shown in this video. https://youtu.be/96_VnqywyRY?si=7UiVWp2RpikjRDHQ?t=240

That should fix the problem.

**Comment by hazmatguy88778** [comment]
so do i just copy the recording files from the previous world and paste it into the new world? or will it bug out?

**Comment by mchorse** [comment]
No, enter into another world, do what shown in the video, and then come back to your original mod that kicks you out/crashes you.
