### ISSUE TITLE
records not loading properly bug

### ISSUE THREAD

**Issue by hazmatguy88778** [mchorse/blockbuster#255]
whenever i action record, and put it into a model block, it works, but when i leave the game it starts to bug out, here's a video

https://github.com/mchorse/blockbuster/assets/134218867/08b1fbef-8d58-4e86-a90b-721895a485ca

**Comment by Chryfi** [comment]
Your description is very vague. What exactly did you put into the model block?

**Comment by hazmatguy88778** [comment]
apologies, but i put a records morph into the model block

**Comment by Chryfi** [comment]
That's because you need to load the recordings again. Playback the scene once and it should work again.
