### ISSUE TITLE
Annoying message appearing don't know how to turn it off

### ISSUE THREAD

**Issue by hazmatguy88778** [mchorse/blockbuster#257]
there's a message that appears and it's very annoying
![bug 1](https://github.com/mchorse/blockbuster/assets/134218867/cd2d1f5e-cde7-489a-8b9f-bc3fe52d44b1)
whenever i aim towards a block, the message appears and i want to find a way to turn it off, is there any option on how to disable it?

**Comment by Chryfi** [comment]
This is not an issue or a bug. You can deactivate this in the settings under damage control label.
