### ISSUE TITLE
1.20.1???

### ISSUE THREAD

**Issue by koenigsegg1agera2rs** [mchorse/blockbuster#272]
When will there be a version of 1.20.1 forge? The problem is that: createmod, cobblemon, and more! Even more want a version of 1.20.1 and there are even people who use other versions like 18 19.2 19.4 and more

**Comment by Chryfi** [comment]
We are working on it, it's not as easy as you think. The mods need to be rewritten from scratch because the original codebase of the mods isn't very good and flexible. It will take a long time.

**Comment by koenigsegg1agera2rs** [comment]
thanks!
