### ISSUE TITLE
Not Burning

### ISSUE THREAD

**Issue by Proman101010** [mchorse/blockbuster#30]
When Morphing as a Zombie/skelton/undead mob you hear Burning sound but you don't burn or take damage.

**Comment by ycwei982** [comment]
You should open this issue at [mchorse/metamorph](https://github.com/mchorse/metamorph/issues), though it shouldn't be blockbuster's fault?

**Comment by mchorse** [comment]
Yeah, right, it's Metamorph's issue, and I think similar issue was posted already in Metamorph's issue tracker.
