### ISSUE TITLE
[Feature Request] Freeze Actor

### ISSUE THREAD

**Issue by The-Fireplace** [mchorse/blockbuster#34]
In the Actor Configuration, I would like to see a Freeze Actor checkbox/button. When enabled, the actor doesn't move, can't be pushed, and doesn't fall. This could be useful for editing the area around the actor without having to remove it and place a new one when finished.

**Comment by mchorse** [comment]
Forgot to close lol

**Comment by The-Fireplace** [comment]
You sure you meant to close this one and not #33 ?

**Comment by mchorse** [comment]
*bangs his head against the wall*

Sorry, I haven't realized it was a new issue :D

You can freeze actors with Aperture's preview feature. Could you specify, though, is this for static actors that don't playback? It looks like you're using the *old way* of recording actors: place down an actor with an egg, use register item to attach it to the director block, and right click while sneaking on it to start recording. Thus the need for the freeze.

You can, however, make actors so they won't be on set, but would spawn then when director block playback starts.

**Comment by The-Fireplace** [comment]
Ah, yes, it seems that I am using the old way. Static actors that don't playback.

**Comment by mchorse** [comment]
Haha, sorry for late response, is the issue resolved

**Comment by The-Fireplace** [comment]
I'll check in to it when I get the chance and see.

**Comment by mchorse** [comment]
I need some answers, because I really want to close this issue 😄

**Comment by The-Fireplace** [comment]
Alright, sorry. I'm in the process of packing everything so I can move, it
will be a few days before I can answer. I will go ahead and close it, and I
will re-open it if it is still an issue.

On Aug 10, 2017 11:59 AM, "Sir McHorse" <notifications@github.com> wrote:

I need some answers, because I really want to close this issue 😄

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mchorse/blockbuster/issues/34#issuecomment-321611869>,
or mute the thread

**Comment by The-Fireplace** [comment]
Well, if you could make it possible to freeze static actors that don't play back, it would certainly solve the issue. One of my projects involves taking screenshots of the actors standing still, which works better with the old actors than the new method.

**Comment by ycwei982** [comment]
I think you can just spawn an actor and use actor configure device, but not link to director block

**Comment by The-Fireplace** [comment]
@ycwei982 Sorry if I wasn't clear, I know I can do that, but I would like to be able to freeze the spawned actor so I can, for example, break a block below it, and the actor not fall.

**Comment by mchorse** [comment]
@The-Fireplace like in [this video](https://www.youtube.com/watch?v=RUTm5jLDss4)?

**Comment by The-Fireplace** [comment]
No, like just for the actor entity, not anything to do with looking at a recording. If it still isn't clear, I'll just do it myself and make a PR.

**Comment by mchorse** [comment]
Wait... I think I got what you mean, and IMO it is a very good idea! You want like a checkbox/flag that allows to disable any motion applied to the actor entity. I would be able to add that somewhere on weekend. If you cool with it, cool, otherwise feel free to PR. Could you please implement it in the `dev` branch?

Also, you will need to build dev builds of Metamorph and Aperture mods using gradle, and place them in the `run/mods` folder.

**Comment by The-Fireplace** [comment]
Awesome, you get it! Finally, I managed to explain it clearly(watching the
videos on blockbuster and seeing what you thought when I said actor
helped). I'm in no hurry, there are other parts to my project that I am
working on as well, that will take some time.

**Comment by mchorse** [comment]
Alright, cool! By the way, once you'll finished with that project, would you mind sharing video with me? :)

**Comment by The-Fireplace** [comment]
Sure! The part of the project I need this for is just about screenshots, but if there is a video(I want to have at least one), I will definitely share it with you.

**Comment by mchorse** [comment]
@The-Fireplace hey, are you there? I implemented this in the dev, and tell me if this is what you wanted. I basically added a checkbox "Freeze this actor?" in GUI when you right click with **actor configuration** item.

**Comment by The-Fireplace** [comment]
Exactly what I wanted. Thanks!

**Comment by mchorse** [comment]
👌
