### ISSUE TITLE
How to constribute?

### ISSUE THREAD

**Issue by DR4RCON** [mchorse/blockbuster#35]
How to constribute or join a discussion? I would like to get into it, planning to maximize the automization of entities. I suggest training a villager as example to do showned things in a loop. That should include the using of all integrated blocks, like chest or (a future dream) ME System or other blocks of mods.
Automization through villagers or any other kind of entity.

Regards, Drarcon

**Comment by mchorse** [comment]
What? Uhm, this mod os for creating machinimas, rather than for automation. However, yeah, it might be possible to use it for automation, but due to how restricted recording of player actions, it's just not as usable as it could be.
