### ISSUE TITLE
1.10.2 not actually morph problem

### ISSUE THREAD

**Issue by FOXTrot4** [mchorse/blockbuster#37]
when i kill a mob, they die...but then a hollow NPC with their name pops up in their place. this, clearly, is not right.

[ and ] also do nothing.

**Comment by FOXTrot4** [comment]
also i could really use another link, literally borderline everywhere i go a source to 1.10.2 version is non-existent or "updating".

**Comment by mchorse** [comment]
Which version of Metamorph do you use and where did you downloaded it? By the way, that's Blockbuster's issue tracker...
