### ISSUE TITLE
Crash when actor uses crossbow from crossbow mod or reforged mod

### ISSUE THREAD

**Issue by koalaGP** [mchorse/blockbuster#38]
[crash-2017-08-25_12.56.02-server.txt](https://github.com/mchorse/blockbuster/files/1251226/crash-2017-08-25_12.56.02-server.txt)

**Comment by mchorse** [comment]
I'll take a better look once I'll return to Blockbuster development.

**Comment by mchorse** [comment]
Hm, I took a look at the code, and I'm not sure where exactly the problem. *gets technically* I tried debugging by downloading deobfuscated jars, but unfortunately there is no source jar on Reforged's GitHub for 1.10.2.

Also I can't waste much of my time on some bug that I plan to fix in the future universally for much broader variety of bugs.
