### ISSUE TITLE
Crashing (with Metamorph 1.1.4)

### ISSUE THREAD

**Issue by TheZeroAssassin** [mchorse/blockbuster#43]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Blockbuster (blockbuster)

**Comment by ycwei982** [comment]
Are you using Metamorph v1.1.4? Before Blockbuster 1.4.9 was released, you should keep using Metamorph v1.1.3.

**Comment by TheZeroAssassin** [comment]
Ooh. That fixed my problem, I didn't realize this. So sorry it was that simple
I'm not good with fixing crashing

**Comment by ycwei982** [comment]
Maybe a issue from Open to Close, this is fastest I have ever seen lol

**Comment by mchorse** [comment]
@ycwei982 good idea, and thanks for pointing that out! 👍
