### ISSUE TITLE
About new way to build lang files and some other dev questions

### ISSUE THREAD

**Issue by ycwei982** [mchorse/blockbuster#44]
I found using ./gradlew build cant really pass that `buildLangFiles` unless I created a new blank lang files in assest dir. So is creating new blank lang files must needed? or is it just a bug of premission?

**Comment by mchorse** [comment]
Yeah, I feel like it's a bug with permissions or something, because at my end, everything works fine

**Comment by ycwei982** [comment]
is there any `-dev.jar` released? now I build mods by copying *sources* of **Metamorph and Aperture** to `src/main/java/mchorse`... then the mod got 3-in-one...

**Comment by mchorse** [comment]
I think not, you gotta build the dev jars yourself. About 3-in-1 thing, I think you can do that automatically somehow by shadowing jars with gradle. I'm not 100% sure how to do it, though.
