### ISSUE TITLE
How to delete actor?

### ISSUE THREAD

**Issue by thenoobi** [mchorse/blockbuster#47]
Im using egg spawner, and how to delete actor after spawning actor?

any "despawn egg" tools or commands?

**Comment by ycwei982** [comment]
Kill the actor with your diamond sword.

**Comment by mchorse** [comment]
Or...

```
/kill @e[type=blockbuster:actor]
```

(replace `blockbuster:actor` with `blockbuster.Actor` for 1.10.2)

**Comment by thenoobi** [comment]
Thanks for your answer. 
I hope you add delete option with actor configurator in next updates.

Cheers..

**Comment by mchorse** [comment]
Maybe 🤔
