### ISSUE TITLE
Small issue just one i wanted to ask about. (now resolved.)

### ISSUE THREAD

**Issue by kanan3662** [mchorse/blockbuster#48]
For an upcoming project i require that I have two limbs both using unique models and both attached to the same actor, is there something I can do about that of will it require a new updated version?

**Comment by kanan3662** [comment]
I can explain further. I require that one custom 3d model is attached to an actor's head and one is attached to it's because body. Any thoughts? Version is the newest 1.10 file.

**Comment by ycwei982** [comment]
The only idea I can think is to use a model editing software, import 2 OBJ files in one project, then restructure it.

**Comment by kanan3662** [comment]
and how would do that?

**Comment by ycwei982** [comment]
I think *Blender3D* is enough to do that?

**Comment by kanan3662** [comment]
well, to be honest I do not know my way around most 3d modelling programs. I may need further advice  on what i'm doing.

**Comment by mchorse** [comment]
Yes, your best bet is on using Blender3d, creating the model there and then exporting it as OBJ. There is a turorial on my channel on how to import OBJ models to Blockbuster.

**Comment by kanan3662** [comment]
I know how to make the models. but, I cannot apply more than one model to a custom actor.

**Comment by kanan3662** [comment]
small update: suggested methods are unable to be rendered by blockbuster. 2 models in one file does not work in general. and as for telling me to just use blender that doesn't work either. i'm stuck with one model and a small cube or none of the models loading.

**Comment by mchorse** [comment]
Watch the video on my chanel. It shows how to load one model, correct, but you can apply this technique to multiple limbs. I.e. in blender, you have two objects, mesh1 and mesh2, you export it as OBJ, then in in-game model editor, you create 2 limbs: mesh1 and mesh2, and if you done everything explained in the video correctly, you would be able to have these two models independent from each other.

**Comment by kanan3662** [comment]
thanks for that. :)

**Comment by kanan3662** [comment]
it didn't work. and before you say I didn't follow the video correctly, I followed it frame by frame.

**Comment by kanan3662** [comment]
considering it worked, I officially love you. you are the best mod creator I've seen in a long time to take time out of your day to help me with this.
