### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by Vyablee** [mchorse/blockbuster#50]
https://github.com/mchorse/blockbuster/blob/2a78623864fb513ee3aeedcbe701df78e5eaa5fc/src/main/java/mchorse/blockbuster/recording/actions/AttackAction.java#L37

My mocaps are using 5 block reach

**Comment by Vyablee** [comment]
Please get them banned on hypixel and mineplex

**Comment by mchorse** [comment]
Not really an issue.
