### ISSUE TITLE
crashes when it loads 

### ISSUE THREAD

**Issue by heybuddies** [mchorse/blockbuster#53]
ill push play and before it opens it crashes and says "Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Blockbuster (blockbuster) "  i am unsure of what to do. im really interested in this mod but i cant play with it ;/. Any clue on whats wrong?

**Comment by mchorse** [comment]
@heybuddies I need the crash log. This message doesn't provide anything useful (preferably uploaded on pastebin.com).

**Comment by heybuddies** [comment]
[crash-2018-04-10_21.34.47-client.txt](https://github.com/mchorse/blockbuster/files/1899134/crash-2018-04-10_21.34.47-client.txt)  
im new to all this......idk if I've done it right or not.

**Comment by mchorse** [comment]
You have to update Metamorph to version 1.1.4. You have currently 1.1.3. Download it on CurseForge: https://minecraft.curseforge.com/projects/metamorph/

**Comment by heybuddies** [comment]
thank you! It opened then this happened....
![2018-04-11_13 52 00](https://user-images.githubusercontent.com/38272310/38642847-3184f93e-3d90-11e8-804a-9005822dc871.png)

**Comment by heybuddies** [comment]
was this supposed to happen?

**Comment by mchorse** [comment]
You need to download the 1.12 build. It looks like you pressed the download latest button. Click on Files button (on that CurseForge page) and find the 1.12 build of Metamorph.

**Comment by ycwei982** [comment]
For your current status:

- Click the *Button 1* **ONLY ONCE**.
- Type which key you want to use on the keyboard **ONLY ONCE**.
- It should be changed to which key you want to use now
