### ISSUE TITLE
I18n in SubCommandBase

### ISSUE THREAD

**Issue by LatvianModder** [mchorse/blockbuster#65]
https://github.com/mchorse/blockbuster/blob/17ccbdbb7a186bf90ab62dda5ddf0fff09e8c651/src/main/java/mchorse/blockbuster/commands/SubCommandBase.java#L66-L77

This is completely wrong. getCommandUsage() returns an unlocalized string like "commands.name.usage", not translated one. Also caused this crash, because you are using client-side-only class on server side:
https://github.com/LatvianModder/FTBUtilities/issues/846

Why do you have your own class at all? CommandTreeBase exists

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBQuests/tree/master/src/main/java/com/feed_the_beast/ftbquests/command
You can take a look here for example (CommandFTBQuests being the main one here). And you can have CommandTreeBase children too, thus, tree command

**Comment by mchorse** [comment]
Ah, I see, I'll try it out when I'll have chance.

**Comment by mchorse** [comment]
Fixed by simply returning the language string of the command. I don't really want to deal with `CommandTreeBase`.
