### ISSUE TITLE
Invisible armor from "Extra Bit Manipulation".

### ISSUE THREAD

**Issue by olegikoligik** [mchorse/blockbuster#67]
When i install blockbuster and metamorph, chiseled armor from "Extra Bit Manipulation" mod becomes invisible. It influences both the player, and the actor.
![2018-09-17_23 35 56](https://user-images.githubusercontent.com/22132987/45648860-60849400-bad2-11e8-9cf0-399890626b04.png)

![2018-09-17_23 29 43](https://user-images.githubusercontent.com/22132987/45648550-91b09480-bad1-11e8-9ecf-2acc25de49b2.png)

P.S. Tell me if you need more info.

**Comment by mchorse** [comment]
Which version of Blockbuster and Metamorph do you use? And also, is that your actual default skin? Or are you morphed into custom model morph?

As far as I can tell, the way this mod works is requires a special render layer to be present. However, those work only with players, and I can't really do anything about it.

**Comment by olegikoligik** [comment]
blockbuster-1.5.1-1.12.2, metamorph-1.1.6-1.12.2
Yes, it default skin.

**Comment by mchorse** [comment]
Hm, in that case, I'll take a look at it.

**Comment by mchorse** [comment]
Apparently, it was a bug with Metamorph, rather than with Blockbuster. This fix will be out once `1.1.7` update will be out. 

It would be still impossible to use this feature with Blockbuster custom models or any morphs, but... You could still use player morphs or no morphed Fake Player actors.
