### ISSUE TITLE
Posing Issue

### ISSUE THREAD

**Issue by Lilee2** [mchorse/blockbuster#68]
Hello, I'm not sure what keeps happening, but whenever I go to edit one of the player recordings I've created, the morph effect & poses don't save. This is in the latest updated version of the mod.

**Comment by mchorse** [comment]
Yeah, I accidentally broke that in `1.5.1`. :sweat: Roll back to 1.5, please. I'll post a fix update ASAP.

**Comment by mchorse** [comment]
Fixed in `1.5.2`.
