### ISSUE TITLE
blockbuster 1.5.3 crashing

### ISSUE THREAD

**Issue by TheWesternRider** [mchorse/blockbuster#76]
I press launch minecraft and it crashes upon start up.

**Comment by ycwei982** [comment]
Please provide a crash log, or we can't diagnose the problem.

Paste it through [Pastebin](https://pastebin.com) or [Ubuntu Paste](https://paste.ubuntu.com).

**Comment by TheWesternRider** [comment]
https://paste.ubuntu.com/p/n3cZ37hWWj/ (game output crash log thingy)

**Comment by TheWesternRider** [comment]
fixed it I needed aperture 2

**Comment by mchorse** [comment]
@TheWesternRider yeah, in the change log it's stated that you need at least Aperture 1.2. It's nice that you was able to solve it. 🙂
