### ISSUE TITLE
Wheel bug

### ISSUE THREAD

**Issue by STEVEGAMERPRO** [mchorse/blockbuster#78]
The wing works but the wheel is bug I tried to change the anchor point but nothing

![ezgif-1-315912f99fc7](https://user-images.githubusercontent.com/48246416/53804671-71be4180-3f48-11e9-9fde-805b47c0f881.gif)

**Comment by mchorse** [comment]
Use `OBJ origin` field to setup an anchor point, and then move the propeller back again. Second of all, wheel works only if the running (the legs icon in the bottom middle bar) is clicked.
