### ISSUE TITLE
How to use/Record Emoticons with Blockbuster?

### ISSUE THREAD

**Issue by thenoobi** [mchorse/blockbuster#80]
In this video:
https://youtu.be/_J3jeENTDJs

you are using blockbuster, aperture and emoticons right?

But when I try to record an actor its seem not working, walk still vanilla, i cant press emoticons shortcut.. etc.

has something been missed?
Or any tutorial for doing that?

**Comment by mchorse** [comment]
Come to my [Discord server](https://discord.gg/qfxrqUF), I'll explain there.
