### ISSUE TITLE
Moving Morph

### ISSUE THREAD

**Issue by LemonStub** [mchorse/blockbuster#91]
for some reason when I turn into any mob other than an ocelot it sends that mob into a random direction without me controlling it. I don't know why this is happening but I really enjoy the mod because of how useful and fun it is.

**Comment by mchorse** [comment]
If that happens, it's a mod incompatibility where another mod tries to modify player's hitbox as well. Some of the known mods to do that is Tropicraft. If it still persist after uninstalling Tropicraft, I would recommend you either checking mods one by one that causes this issue, or disable hitbox modification in Metamorph's mod options (I'm not sure if there is, but there might be such option, I don't remember).

**Comment by LemonStub** [comment]
Ok thank you.

**Comment by LemonStub** [comment]
Thank you for bringing to my attention that the tropicraft mod makes the
mobs move without you telling it to, I've found that if you go into config
for tropicraft and turn off the swimming animation that then it fixes this
issue :]

**Comment by mchorse** [comment]
Awesome! 🙂 👍
