### ISSUE TITLE
Galacticraft space items compatibility?

### ISSUE THREAD

**Issue by ZelouiixDev** [mchorse/blockbuster#93]
Hi,

I am desperately trying to make my actors wear the space items of Galacticraft Mod (like the oxygen tanks and the oxygen mask). But when I record and playback, these items do not appear on my actors morph. They are ordinary "blockbuster.steve" morph with a custom skin. 

When I record with a "Player" morph, the Galacticraft items do appear, but I cannot custom the skin (I have to enter a player name and not a texture). I am guessing the "blockbuster.steve" morph is not exactly the same model as the "Player" morph.

Is there a way to make those items appear on the blockbuster.steve morph?

Thank you for your answer!

**Comment by mchorse** [comment]
Sorry, I don't check GitHub very often. I answered you on CurseForge in [the comments](https://www.curseforge.com/minecraft/mc-mods/blockbuster?comment=152).
