### ISSUE TITLE
Wen I press the Record button The game crash

### ISSUE THREAD

**Issue by RedWavs** [mchorse/blockbuster#96]

**Comment by RedWavs** [comment]
the crash log : ---- Minecraft Crash Report ----

WARNING: coremods are present:
  McLib core mod (mclib-1.0.3-1.12.2.jar)
  BlockbusterCore (blockbuster-1.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 7/19/19 4:40 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at mchorse.blockbuster.common.tileentity.director.Replay.apply(Replay.java:84)
	at mchorse.blockbuster.common.tileentity.TileEntityDirector$1.run(TileEntityDirector.java:231)
	at mchorse.blockbuster.recording.RecordManager$ScheduledRecording.run(RecordManager.java:388)
	at mchorse.blockbuster.recording.ActionHandler.checkScheduled(ActionHandler.java:501)
	at mchorse.blockbuster.recording.ActionHandler.onWorldTick(ActionHandler.java:443)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_ActionHandler_onWorldTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 538637240 bytes (513 MB) / 1577058304 bytes (1504 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 9 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID               | Version      | Source                        | Signature                                |
	|:--------- |:---------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft        | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp              | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML              | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge            | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mclib            | 1.0.3        | mclib-1.0.3-1.12.2.jar        | None                                     |
	| UCHIJAAAA | metamorph        | 1.1.8        | metamorph-1.1.8-1.12.2.jar    | None                                     |
	| UCHIJAAAA | blockbuster      | 1.6          | blockbuster-1.6-1.12.2.jar    | None                                     |
	| UD        | blockbuster_core | 1.6          | minecraft.jar                 | None                                     |
	| UD        | mclib_core       | 1.0.3        | minecraft.jar                 | None                                     |

	Loaded coremods (and transformers): 
McLib core mod (mclib-1.0.3-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
BlockbusterCore (blockbuster-1.6-1.12.2.jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['RedWavs'/369, l='New World-----------', x=129.73, y=64.00, z=425.97]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by mchorse** [comment]
Thanks for reporting this issue, however, this issue was already fixed in the dev build. Feel free to download and use this [dev build](https://cdn.discordapp.com/attachments/548439751682687016/596399927731683328/blockbuster-1.6.1-1.12.2-dev2.jar).

**Comment by RedWavs** [comment]
thanks ! ^^
