### ISSUE TITLE
Blockbuster does not like MW Guns

### ISSUE THREAD

**Issue by VanillaChan6571** [mchorse/blockbuster#98]
Crash report. Same error every time.
https://hastebin.com/ifoyuriheh.sql

**Comment by mchorse** [comment]
It's not Blockbuster not liking MW guns, but rather MW guns not liking Blockbuster. I can't fix this issue. Use [BB guns](https://youtu.be/wpfiLTrzTLs?t=176) with [custom models](https://www.youtube.com/watch?v=myQiuJTQUFI).
