### ISSUE TITLE
Huge danger

### ISSUE THREAD

**Issue by HatcheryRoosters** [mchorse/blockbuster#99]
I was remaking the Circle of Life from Lion King Broadway, when I tried to do the 5th animal, it said couldn't load camera profile by filename. As a result of this, the 4 animals I already have set up vanish everytime I replay to sync recording.

**Comment by mchorse** [comment]
Why do you posted same issue in a couple of places?

**Comment by HatcheryRoosters** [comment]
I'm the same person as ClaySoldiersistheone

**Comment by mchorse** [comment]
I know, that's the problem. I don't like to track the same issue in multiple places.
